### PR TITLE
Extended useAsync functionality

### PR DESCRIPTION
**Pull request by B3nten**
The current implementation of `useAsync` returns the callback if data is not present when the component mounts, which means if the data on the server doesn't resolve and stream practically instantly, the client will return the callback - which means fetching client side. The data that gets streamed in is ignored. The idea here is that we want to start fetching on the server, and access it on the client. 

I think one approach is to have this hook always return a function that returns a promise. This makes it nicely compatible with fetching libraries and I think it's a decent API. So we can either return a promise to return the data when it streams in, or if we already have the data we can choose to either return it or return the callback.

This way, an end user can do something like this:

```
const mounted = useMount(false)
// ...
useAsync(() => fetch('/api/data'), { returnCallback: mounted })
```

So if the data is already present, it will use it, but subsequent calls will return the callback for refetching. And if the data isn't present, it will return a promise to return the data from the stream when it arrives, and subsequent calls will return the callback for refetching. And if `returnCallback` is always false, it will always return the streamed data without making more requests.

If it's possible, it would be nice to have the hook figure out if data is being streamed - if not, it would make sense to return the callback at that point. Although that can be handled by the client by means of some global `isMounted` state (eg. `globalThis.ultra.mounted = true`) for handling cases like client-side routing.

Let me know what you think of this idea.

(oh, also I have no idea what I'm doing with jsdoc pls help)

### CODE REVIEW

**Comment by deckchairlabs** [comment]
Yeah I like this. I'll add a hook to this PR for mounted, and fix up some of the jsdocs.

**Comment by B3nten** [comment]
I'd consider a global mounted state as well. For example, with client-side routing, it won't stream the data but mounted will equal false.

**Comment by B3nten** [comment]
For example,
```
function useMountedState(global?:boolean): boolean {
    const mounted = useRef(false)
    useEffect(()=>{ 
        mounted.current = true
        globalThis.useAsync = {mounted: true}
     }, [])
    return global ? globalThis.useAsync?.mounted : mounted
}```

**Comment by B3nten** [comment]
I get the global pollution thing, but useMountedState would only really be usable for multi-page apps. Consider what will happen if we do 
```
const isMounted = useMountedState()
const data = useAsync(() => fetch('/api/data'), { returnCallback: isMounted() })
```
on a component that we navigate to client-side. `isMounted()` will return false when the component first mounts, but since nothing is being streamed it will timeout. We really need it to return the callback on mount. It's trivial for a user to set up themselves though.

**Comment by deckchairlabs** [comment]
Ah I see! Right, well I'd leave that to adding a context provider.

```ts
const returnCallback: boolean = useContext(SomeGlobalContext)
const data = useAsync(() => fetch('/api/data'), { returnCallback })
```

**Comment by B3nten** [comment]
> Also, we probably need to wrap callback in `useCallback`, and pass options as a dependency

Or leave that up to the user. Wouldn't wrapping callback in `useCallback` potentially lead to stale closures?

**Comment by deckchairlabs** [comment]
Oh you're right, yes, scratch that.

**Comment by deckchairlabs** [comment]
This should work nicely with the experimental `use(promise)` hook

**Comment by deckchairlabs** [comment]
merged, cheers!

**Pull request merged**
