### PR TITLE
feat(ultra): added rootDirectoryPath option

### PR DESCRIPTION
**Pull request by Industrial**
Implemented the option `rootDirectoryPath` which is set to `"."` by default.

### CODE REVIEW

**Comment by mashaal** [comment]
An option for the root directory path is a great idea (https://github.com/exhibitionist-digital/ultra/issues/23).

Is there a reason why all of the bare imports were replaced here? The general concept is that the pinned versions of dependencies are controlled via an importmap.

**Comment by Industrial** [comment]
Oh, oops. I've made that last commit by mistake. I'll revert it. I was trying to get this to deploy to Deno Deploy and it doesn't support import maps (yet?). After I did this I found out that it also doesn't support dynamic imports.

@mashaal: How did you deploy?

**Review by mashaal — APPROVED** [review]

**Comment by mashaal** [comment]
I tried to merge this manually, but this PR still remains open with a conflict. I might revert the manual merge and maybe we can fix this one up?

**Comment by Industrial** [comment]
See https://github.com/exhibitionist-digital/ultra/pull/30

**Pull request closed without merging**
