### PR TITLE
feat: support unit test for examples && remove dev progress and it's port 4507

### PR DESCRIPTION
**Pull request by ahuigo**
This PR includes 2 features as following.

**1. Support unit test for examples**
```
$ deno run -A  tools/test-examples.ts basic with-csr  with-unocss          
```
image

**2. Remove dev progress and it's port 4507**
For https://github.com/exhibitionist-digital/ultra/issues/235
Ultra  shares one port with App(default 8000)
image

### CODE REVIEW

**Comment by ahuigo** [comment]
@deckchairlabs Can you fix this bug? https://github.com/exhibitionist-digital/ultra/actions/runs/4082917796/jobs/7037820037

**Comment by deckchairlabs** [comment]
> @deckchairlabs Looks like mesozoic has another bug that I don't know. Could you fix this bug? https://github.com/exhibitionist-digital/ultra/actions/runs/4082917796/jobs/7037820037

Yeah, sorry this is taking some time to get fixed. Work gets in the way sometimes! I'll have some time tomorrow to resolve the bug and this PR.

**Comment by deckchairlabs** [comment]
hey @ahuigo I've resolved the failing test issues, could you fix the conflicts (looks simple enough)

**Comment by deckchairlabs** [comment]
Cheers!

**Pull request merged**
