### PR TITLE
feat: add compile hooks to dev server

### PR DESCRIPTION
**Pull request by B3nten**
Adds compile hooks to the compiler middleware of the dev server.

### CODE REVIEW

**Comment by deckchairlabs** [comment]
Sorry benten, still thinking about this. What's your exact use case?

**Comment by B3nten** [comment]
> 

I wrote a compiler that parses source code and removes server code from client bundles. Without the ability to intercept the code before it hits SWC I'd be forced to make a copy of the entire project, apply the transforms, and then point Ultra to this duplicated project. And this would happen on every single save, so I'd have to write a custom file watcher etc. It's almost untenable. Would probably be easier to monkey-patch the dev server, but that's obviously not ideal when it could be supported natively in Ultra.

Exposing these hooks would be very useful for more than just this usecase - it gives devs the freedom to build on top of Ultra. Would be willing to chat about alternatives for my usecase though.

**Comment by deckchairlabs** [comment]
I'm thinking that we should `parse` before transform, so you can manipulate the AST before it's handed to `transform`

**Comment by B3nten** [comment]
> I'm thinking that we should parse before transform, so you can manipulate the AST before it's handed to transform
That's what `beforeTransform` does

**Review by deckchairlabs — APPROVED** [review]
Looks good!

**Pull request merged**
